---
# Source: gatekeeper/templates/upgrade-crds-hook.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    helm.sh/chart: gatekeeper-3.21.1
    app.kubernetes.io/name: gatekeeper
    app.kubernetes.io/instance: gatekeeper
    app.kubernetes.io/version: "3.21.1"
    app.kubernetes.io/managed-by: Helm
    release: gatekeeper
    heritage: Helm
  name: gatekeeper-admin-upgrade-crds
  namespace: 'gatekeeper-system'
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: "hook-succeeded,before-hook-creation"
    helm.sh/hook-weight: "1"
